WIP: Address FAIR review comments
simvue-io/docs pull request #22
Opened 2023-11-22 14:43 UTC by wk9874

Addressing FAIR review comments:

- Added missing methods to Reference docs, closes #10

2024-01-04 08:47 UTC, AbyAbraham21 commented on docs/analysis/metrics.md
Line 127 onwards does not look right. Please check

2024-01-04 08:49 UTC, AbyAbraham21 commented on docs/analysis/metadata.md
Line 127 onwards does not look right. Please check

2024-01-04 08:52 UTC, AbyAbraham21 reviewed
further-docs "Further Documentation" seems to be missing or not referenced correctly, please can you check.

2024-01-08 14:41 UTC, alahiff commented
I don't think having the repeated `View reference documentation` etc is necessary. For example instead of:

![image](https://github.com/simvue-io/docs/assets/1795281/7dea7ec3-a3c6-48c8-95e0-fb54d032ed9b)

have:

![image](https://github.com/simvue-io/docs/assets/1795281/339ccc15-77c2-4cc0-91cd-24091d20bdda)

which to me looks much better.

2024-01-24 09:35 UTC, AbyAbraham21 requested changes
A few changes suggested. Please update and merge

2024-01-30 09:29 UTC, AbyAbraham21 approved these changes

2024-01-30 09:35 UTC, AbyAbraham21 commented
Updated documentation based on FAIR review

2024-01-30 09:39 UTC, merged