FDS Example and Docs
simvue-io/docs pull request #42
Opened 2024-08-16 17:02 UTC by wk9874

- Created new Docker container
- Added entry to Integrations page for FDS connector
- Added FDS example

@kzscisoft could you remove your fds-example docker container please?

2024-09-17 11:33 UTC, AbyAbraham21 commented
Apologies its taken so long to revert back on this. Running a few examples using these docs so can comment once done

2024-09-18 10:46 UTC, AbyAbraham21 requested changes
A couple of minor changes and then it is good to go

2024-09-18 10:46 UTC, AbyAbraham21 commented on docs/examples/fds.md
> +python run_simulation_no_vents.py
@wk9874 : Will be worth adding a warning to have a user token or point to a reference to the same else the user will get an exception

2024-09-18 13:11 UTC, wk9874 commented on docs/examples/fds.md
> +python run_simulation_no_vents.py
This is already in the setup instructions above:

```
### Update Simvue Config File
Finally we need to update the config file inside the Docker container to use your credentials. Login to the web UI, go to the **Runs** page and click **Create new run**. You should then see the credentials which you need to enter into the `simvue.ini` file. Simply open the existing file using `nano simvue.ini`, and replace the contents with the information from the web UI.
```

2024-09-18 13:19 UTC, merged